import React from 'react';
const content={
disclosures:[
['Speculative asset','CFK is a speculative crypto token. Its price can change sharply and you can lose the entire amount you use to buy it. No return, price, liquidity, sale, or payout is guaranteed. Market cap is not the amount of money available for sellers.'],
['Ownership and conflicts','Free Crypto App LLC, Cashflowkey, creators, promoters, affiliates, and related parties may create, promote, hold, buy, or sell CFK and may receive fees. Their interests may differ from yours. CFK does not give you ownership of Free Crypto App LLC, dividends, or a share of its business revenue.'],
['15% platform fees','A 15% platform fee applies to the gross amount added through the payment provider and a separate 15% platform fee applies to the gross amount cashed out through the payment provider. For example, adding $100 leaves $85 before any additional provider or network costs. Cashing out $100 leaves $85 before those additional costs. Coin-protocol and network costs also apply to trades. These trading fees are not the 15% platform fee. A small amount may remain available to cover costs. Selling coins makes proceeds available to withdraw; it does not itself make a bank payout.'],
['Providers and timing','Payment methods, limits, identity checks, eligible countries, settlement times, and extra costs depend on the payment provider. Crypto sales depend on available liquidity. Selling CFK does not itself deposit cash into a bank account. You must complete the provider’s withdrawal process.'],
['Before confirming','Review the dollar amount, price movement allowance, and fees. Blockchain transactions generally cannot be reversed. Quotes are estimates and can expire. The app does not promise instant execution or instant payouts.'],
['Market data and activity','Market data is supplied by external services and may be delayed or unavailable. Activity shows observed transactions from the CFK bonding curve or selected pool. It may not include every transaction. New chart history is collected from actual price observations; a 24-hour change is shown only once comparable data exists. A holder count measures funded token addresses and can include protocol or pool accounts. It is not a count of unique people. Your displayed return is available only when the app can account for your position’s cost.'],
['Not advice','This app and its promotional content do not provide individualized investment, legal, or tax advice. You are responsible for your decisions and any taxes.']
],
terms:[
['Free Crypto App LLC · September 24, 2026','These terms govern Buy $CFK and related software operated by Free Crypto App LLC. By using the service, you agree to these terms and the risk and fee disclosures.'],
['Eligibility','Use the service only if you are at least 18, can enter a binding agreement, and are permitted to use it where you are located. Wallet and payment providers can impose additional requirements, identity checks, limits, or restrictions.'],
['User-directed transactions','You decide whether and how much to buy or sell. Choosing Buy and completing payment authorizes an automatic CFK purchase after the payment is verified. Choosing Sell authorizes a sale of your selected dollar amount at an available price, allowing up to 1% price movement. Cash withdrawal requires completing the payment provider’s process. Execution, price, availability, reversibility, and timing are not guaranteed.'],
['Wallets and third parties','Privy supplies wallet infrastructure. Blockchain, routing, market-data, payment, funding, and withdrawal providers operate under their own terms and policies. Protect your account and devices. We will never ask you to send a recovery phrase or private key to support.'],
['Fees and relationships','The 15% funding fee and 15% withdrawal fee are described in Risk & fee disclosures. Provider, network, and other transaction costs can also apply. Fees are presented before confirmation. We and related parties may hold or transact in CFK and may profit from fees or token ownership.'],
['Acceptable use','Do not use the service for fraud, theft, market manipulation, artificial volume, deceptive coordinated transactions, money laundering, sanctions evasion, unauthorized access, or other unlawful activity.'],
['Availability and responsibility','The service and third-party information are provided as available. You may lose some or all of your money. To the extent permitted by law, we disclaim warranties and liability for indirect losses, third-party failures, market losses, or user error. Nothing excludes rights or liability that applicable law does not permit us to exclude.'],
['Changes and contact','We may update these terms or features for operational, security, or legal reasons. Material changes to these terms will be presented when required. Contact support@freecryptoapp.com with questions.']
],
privacy:[
['Free Crypto App LLC · September 24, 2026','This policy describes how Buy $CFK handles information. Free Crypto App LLC operates this app. Contact support@freecryptoapp.com for privacy questions or requests.'],
['Information used to operate the app','We process wallet addresses, your authenticated wallet-provider identifier, transaction details, funding and withdrawal status, session identifiers, and technical information needed to secure and operate the app. Telegram authentication is handled through Privy when enabled. Wallets and blockchain transactions are public records.'],
['Advertising measurement','With your measurement permission, we retain click identifiers, campaign tags, referral source, browser identifiers, IP address, user agent, and conversion events. Configured advertising partners may include Google/YouTube, Meta, X, TikTok, and OpenAI. Purchase conversion value represents our attributable platform-fee revenue, not the full amount of crypto you buy.'],
['Your choices','Choose essential-only use to disable optional advertising measurement, or change your choice in Privacy choices. Global Privacy Control is treated as a request to disable advertising measurement. Declining measurement does not prevent buying or selling. Essential security, transaction records, and provider requirements still apply.'],
['Payments and wallets','Privy and payment providers process login, wallet, identity-verification, and payment information under their policies. Card information is entered with the provider, not stored by this app. Never send card details or wallet secrets to support.'],
['Sharing and storage','We use hosting, database, wallet, payment, blockchain, routing, and market-data services to operate the app. Optional conversion information is sent only to configured advertising services when permitted. We retain operational records as necessary to provide the service, resolve issues, and meet legal obligations. Attribution sessions expire after 30 days; transaction records may be retained longer.'],
['Requests and limitations','You may contact us to request access, correction, or deletion where applicable. We cannot delete public blockchain records. Depending on the provider and your location, some information may be processed in other countries. The app is not intended for children.']
]};
export default function Legal({kind}){return <div className="legal">{content[kind].map(([title,body])=><section key={title}><h3>{title}</h3><p>{body}</p></section>)}<p><a href="mailto:support@freecryptoapp.com">support@freecryptoapp.com</a></p></div>;}
